#:schema https://dystroy.org/bacon/.bacon.schema.json

default_job = "backend"

need_stdout = true
allow_warnings = true
background = true
show_command_error_code = true
scroll_anchor = "auto"

[jobs.backend]
command = ["cargo", "run"]
background = false
on_change_strategy = "kill_then_restart"

[jobs.frontend]
command = ["cargo", "run"]
background = false
on_change_strategy = "kill_then_restart"

[keybindings]
b = "job:backend"
f = "job:frontend"
